// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Destination is the resolved answer to a folder pick, so the UI can show the
 * exact path and the space arithmetic before anything is moved.
 */
export interface Destination {
    "target": string;
    "directory": string;
    "cancelled": boolean;
    "bytes": number;
    "freeBytes": number;
    "sameVolume": boolean;
    "enoughSpace": boolean;

    /**
     * Resumable marks a destination that already holds part of this directory
     * from an interrupted attempt. ResumedBytes is how much of it is there, so
     * the confirmation can promise a continuation rather than a fresh copy.
     */
    "resumable": boolean;
    "resumedBytes": number;
    "unavailable": string;
}

/**
 * Location describes one relocatable directory for the settings page.
 */
export interface Location {
    "target": string;

    /**
     * Directory is what Nonoka X uses right now, relocated or not.
     */
    "directory": string;
    "default": string;
    "custom": boolean;

    /**
     * Missing marks a recorded directory that is not there any more, which is
     * what an unplugged external drive looks like. Nonoka X keeps pointing at it
     * rather than quietly reinstalling gigabytes somewhere else.
     */
    "missing": boolean;
    "bytes": number;
    "files": number;
    "freeBytes": number;
    "volume": string;

    /**
     * Estimated is how much this directory is expected to grow to. Only the
     * runtime has a meaningful figure: the video cache is bounded by a limit the
     * user sets rather than by what has to be downloaded.
     */
    "estimated": number;

    /**
     * Empty reports that nothing has been installed here yet, which is the one
     * moment choosing a drive costs nothing — there is no data to move.
     */
    "empty": boolean;

    /**
     * EnoughSpace compares the volume's free space against Estimated. False is
     * what turns the install page's location notice into a warning.
     */
    "enoughSpace": boolean;
}

/**
 * RelocationProgress is the live state of at most one move. It is both the
 * return value of the actions and the payload of the storage:progress event.
 */
export interface RelocationProgress {
    "schema": number;
    "active": boolean;
    "target": string;
    "source": string;

    /**
     * Destination is where the move is going, or where the last one went.
     */
    "destination": string;

    /**
     * Stage is one of idle, preparing, moving, finishing, completed, cancelled,
     * failed.
     */
    "stage": string;
    "message": string;
    "completed": number;
    "total": number;
    "error": string;
}

/**
 * StorageStatus is what the settings card renders.
 */
export interface StorageStatus {
    "schema": number;
    "dataDirectory": string;
    "locations": Location[] | null;
    "progress": RelocationProgress;
}

/**
 * VideoExportDraft describes the immutable snapshot held for an independent
 * export window. The potentially large ASS text stays in Go and is never sent
 * back through the webview bridge.
 */
export interface VideoExportDraft {
    "jobId": string;
    "progressId": string;
    "mediaId": string;
    "defaultName": string;
    "t0": number;
    "t1": number;
    "rangeLabel": string;
    "missingFonts": string[] | null;
}

export interface VideoExportResult {
    "path": string;
    "size": number;
}
