// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService coordinates the home, editor and independent video-export
 * windows. The editor owns its unsaved-change UI; native close requests are
 * forwarded to it and only CloseEditor is allowed to destroy that window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseEditor is called only after the editor has resolved its unsaved state.
 */
export function CloseEditor(): $CancellablePromise<void> {
    return $Call.ByID(2775320491);
}

export function CloseVideoExport(): $CancellablePromise<void> {
    return $Call.ByID(530079975);
}

export function OpenEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(2785033743, id);
}

/**
 * OpenVideoExport creates one modeless native export window. One window is
 * enough for now: while it exists a second request focuses it instead of
 * replacing the subtitle snapshot of a running encode.
 */
export function OpenVideoExport(mediaID: string, defaultName: string, ass: string, t0: number, t1: number, rangeLabel: string, missingFonts: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4290372443, mediaID, defaultName, ass, t0, t1, rangeLabel, missingFonts);
}

/**
 * RunVideoExport owns the long-running call on behalf of the export window.
 * The source, subtitle text and output range come only from the stored draft;
 * the renderer can change encoding knobs but cannot silently swap the project.
 */
export function RunVideoExport(jobID: string, crf: number, preset: string, scaleH: number, abr: string): $CancellablePromise<$models.VideoExportResult> {
    return $Call.ByID(2182945304, jobID, crf, preset, scaleH, abr);
}

export function VideoExportDraft(jobID: string): $CancellablePromise<$models.VideoExportDraft> {
    return $Call.ByID(2976517558, jobID);
}
