// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelDownload interrupts the running download. Killing the process is what
 * actually stops it: yt-dlp has no gentler protocol, and the context it runs
 * under is already the timeout's, so cancelling that covers both paths.
 */
export function CancelDownload(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(3321726793, pluginID);
}

export function CancelEngineTask(pluginID: string, taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(928340474, pluginID, taskID);
}

export function ClearCookies(pluginID: string): $CancellablePromise<$models.DownloaderSettings> {
    return $Call.ByID(1670581179, pluginID);
}

/**
 * ClearDownloadLog empties the retained log. It clears the host's buffer, not
 * just the page's view: the page re-fetches on every mount, so wiping only the
 * DOM would bring the whole log back the next time the user navigated away and
 * returned.
 */
export function ClearDownloadLog(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(128034390, pluginID);
}

/**
 * Document returns the stored EditDocument for a media entry. The plugin names
 * the media by the id media.list handed it, never by path.
 */
export function Document(pluginID: string, mediaID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2180736454, pluginID, mediaID);
}

/**
 * DownloadLogLines returns the running -- or most recently finished -- run's
 * output, so a page can render the history it missed. It survives past the end
 * of a run deliberately: coming back after a download finished should still show
 * what happened, and the buffer is cleared when the next one starts.
 */
export function DownloadLogLines(pluginID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2861991218, pluginID);
}

/**
 * EngineArtifacts lists what a run produced, by name and size.
 */
export function EngineArtifacts(pluginID: string, taskID: string): $CancellablePromise<$models.EngineArtifact[] | null> {
    return $Call.ByID(2736732568, pluginID, taskID);
}

export function EngineTaskEvents(pluginID: string, taskID: string, afterCursor: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2772313565, pluginID, taskID, afterCursor);
}

/**
 * EngineTaskStatus, EngineTaskEvents and CancelEngineTask are the page's
 * polling surface, the same one the app's own pipeline view uses.
 */
export function EngineTaskStatus(pluginID: string, taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(171016590, pluginID, taskID);
}

/**
 * ExportAudio is a structured FFmpeg capability. Plugins select a Nonoka X media
 * ID and an output format; the host owns input resolution, arguments, the save
 * dialog, temporary files, and final publication.
 */
export function ExportAudio(pluginID: string, mediaID: string, format: string): $CancellablePromise<$models.ExportedArtifact> {
    return $Call.ByID(968742781, pluginID, mediaID, format);
}

/**
 * ExportVideo burns plugin-supplied ASS into a library video. The plugin owns
 * the subtitle text and the range; the host owns FFmpeg, the encoding
 * settings, the save dialog and atomic publication, exactly as the editor's
 * own export does.
 */
export function ExportVideo(pluginID: string, mediaID: string, fileName: string, ass: string, t0: number, t1: number, scaleHeight: number): $CancellablePromise<$models.ExportedArtifact> {
    return $Call.ByID(2822191320, pluginID, mediaID, fileName, ass, t0, t1, scaleHeight);
}

/**
 * Install accepts a .nonoka-plugin ZIP or an unpacked plugin directory. The
 * directory form is intended for developer workflows and automated tests.
 */
export function Install(path: string): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(2389093410, path);
}

/**
 * LLMComplete runs one call on the user's configured models.
 */
export function LLMComplete(pluginID: string, request: $models.LLMRequest): $CancellablePromise<$models.LLMAnswer> {
    return $Call.ByID(1776205425, pluginID, request);
}

export function List(): $CancellablePromise<$models.InstalledPlugin[] | null> {
    return $Call.ByID(920280027);
}

/**
 * LoadDownloaderSettings reports what the downloader is configured with. The
 * cookie jar is summarised, never returned.
 */
export function LoadDownloaderSettings(pluginID: string): $CancellablePromise<$models.DownloaderSettings> {
    return $Call.ByID(2974810881, pluginID);
}

export function MediaList(pluginID: string): $CancellablePromise<$models.MediaSummary[] | null> {
    return $Call.ByID(701263201, pluginID);
}

export function PageHTML(pluginID: string, toolID: string): $CancellablePromise<string> {
    return $Call.ByID(2703258909, pluginID, toolID);
}

export function PickAndInstall(): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(2263100406);
}

/**
 * ReadArtifact returns a text artifact's content.
 */
export function ReadArtifact(pluginID: string, taskID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3394409097, pluginID, taskID, name);
}

/**
 * RunYTDLP executes plugin-supplied yt-dlp arguments from a closed safe set for
 * public YouTube and Twitch URLs. The host still owns tool resolution, the
 * output path, FFmpeg wiring and the final media-library import.
 */
export function RunYTDLP(pluginID: string, rawURL: string, pluginArgs: string[] | null): $CancellablePromise<$models.DownloadedMedia> {
    return $Call.ByID(1243976307, pluginID, rawURL, pluginArgs);
}

/**
 * SaveArtifact writes an artifact wherever the save dialog says. This is the
 * only way a binary artifact leaves the host, and the plugin's file name is a
 * suggestion: the directory is the user's, as with every other export.
 */
export function SaveArtifact(pluginID: string, taskID: string, name: string, fileName: string): $CancellablePromise<$models.ExportedArtifact> {
    return $Call.ByID(1918735596, pluginID, taskID, name, fileName);
}

export function SaveCookies(pluginID: string, content: string): $CancellablePromise<$models.DownloaderSettings> {
    return $Call.ByID(967913957, pluginID, content);
}

/**
 * SaveDocument writes the editable part of a document back. The payload is
 * rebuilt from the fields the sidecar accepts, so a plugin can neither invent
 * document fields nor drop the revision that guards a concurrent editor save.
 */
export function SaveDocument(pluginID: string, mediaID: string, document: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1672577811, pluginID, mediaID, document);
}

/**
 * SaveSubtitleFile publishes plugin-built subtitle text through the host save
 * dialog. The plugin picks the content and a suggested name; the user picks
 * where it lands, and the host owns the extension.
 */
export function SaveSubtitleFile(pluginID: string, fileName: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(1181628, pluginID, fileName, content);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(859294938, id, enabled);
}

/**
 * StartEngineTask runs the pipeline up to one stage on a library media entry.
 */
export function StartEngineTask(pluginID: string, request: $models.EngineTaskRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1915391222, pluginID, request);
}

export function Uninstall(id: string, removeData: boolean): $CancellablePromise<void> {
    return $Call.ByID(3533390575, id, removeData);
}
