// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sidecar$0 from "../sidecar/models.js";

/**
 * CancelRuntimeInstall stops the running provisioning job. The sidecar cancels
 * cooperatively and keeps whatever it already downloaded, so this is a stop
 * rather than a rollback.
 */
export function CancelRuntimeInstall(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2699265785);
}

export function CancelTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(222136687, taskID);
}

export function Capabilities(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2454552558);
}

export function Document(videoID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3574782081, videoID);
}

export function DocumentPeaks(videoID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(439805167, videoID);
}

/**
 * ImportDocument turns a finished subtitle axis into an editable document
 * without running a task: a bilingual or translated file has nothing left for
 * the engine to compute.
 */
export function ImportDocument(payload: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4000625540, payload);
}

export function InstallPython(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(856516621);
}

export function InstallRuntime(target: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(477675293, target);
}

/**
 * LLMComplete runs one routed LLM call on the user's configured models. The
 * sidecar owns the whole request shape -- roles, prompt size, output budget --
 * so this is a forwarder rather than a second validator that could disagree
 * with the first.
 */
export function LLMComplete(request: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2128011860, request);
}

export function ListTasks(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2672597986);
}

export function PythonBootstrapStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2156410106);
}

/**
 * RemoveRuntime removes replaceable managed environments and caches. The
 * sidecar preserves tasks, subtitle documents, and user settings.
 */
export function RemoveRuntime(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3223749796);
}

/**
 * RemoveRuntimeGroup removes one managed optional-tool group without touching
 * the required runtime, models, tasks, subtitles, or user settings.
 */
export function RemoveRuntimeGroup(target: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3789074711, target);
}

export function ResumeTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2307289594, taskID);
}

export function RetryTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3087477991, taskID);
}

export function RuntimeProvisionStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2693622453);
}

export function SaveDocument(videoID: string, document: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(511995828, videoID, document);
}

export function SaveKeys(keys: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(585136301, keys);
}

/**
 * SetDocumentAxis records the imported subtitle axis a run on this video must
 * land on, or clears it when axis is nil. It is stored beside the document
 * rather than carried in the TaskRequest because the projection consumes it,
 * and a cloud task's artifacts are projected locally without its request ever
 * reaching the sidecar.
 */
export function SetDocumentAxis(videoID: string, axis: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3160308064, videoID, axis);
}

export function Settings(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(957267381);
}

export function SidecarStatus(): $CancellablePromise<sidecar$0.Snapshot> {
    return $Call.ByID(2969168325);
}

export function StartTask(request: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(810889009, request);
}

export function TaskArtifacts(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2554763544, taskID);
}

export function TaskEvents(taskID: string, afterCursor: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3170330684, taskID, afterCursor);
}

export function TaskStatus(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1915716599, taskID);
}
